/* APEXONE USER STORAGE CORRECTION */
ALTER SESSION SET CONTAINER = FREEPDB1;
SET SERVEROUTPUT ON
SET FEEDBACK ON
WHENEVER SQLERROR EXIT FAILURE ROLLBACK

BEGIN
    EXECUTE IMMEDIATE 'ALTER USER APEXONE DEFAULT TABLESPACE APEXONE_DATA';
    EXECUTE IMMEDIATE 'ALTER USER APEXONE TEMPORARY TABLESPACE TEMP';
    EXECUTE IMMEDIATE 'ALTER USER APEXONE QUOTA UNLIMITED ON APEXONE_DATA';
    EXECUTE IMMEDIATE 'ALTER USER APEXONE QUOTA UNLIMITED ON APEXONE_INDEX';
    EXECUTE IMMEDIATE 'ALTER USER APEXONE QUOTA UNLIMITED ON APEXONE_AUDIT';
    EXECUTE IMMEDIATE 'ALTER USER APEXONE QUOTA 0 ON USERS';
END;
/
SELECT username, default_tablespace, temporary_tablespace FROM dba_users WHERE username='APEXONE';
COMMIT;
EXIT
