/* APEXONE AUDIT STORAGE CORRECTION - run once as APEXONE */
SET SERVEROUTPUT ON
SET FEEDBACK ON
WHENEVER SQLERROR EXIT FAILURE ROLLBACK

PROMPT ==========================================
PROMPT APEXONE AUDIT STORAGE CORRECTION
PROMPT ==========================================

ALTER TABLE APP_LOGIN_HISTORY MOVE TABLESPACE APEXONE_AUDIT;
ALTER INDEX PK_APP_LOGIN_HISTORY REBUILD TABLESPACE APEXONE_AUDIT;
ALTER INDEX PK_APP_SECURITY_AUDIT REBUILD TABLESPACE APEXONE_AUDIT;

SELECT table_name, tablespace_name
FROM user_tables
WHERE table_name IN ('APP_LOGIN_HISTORY','APP_SECURITY_AUDIT')
ORDER BY table_name;

SELECT index_name, table_name, tablespace_name, status
FROM user_indexes
WHERE index_name IN ('PK_APP_LOGIN_HISTORY','PK_APP_SECURITY_AUDIT')
ORDER BY index_name;

COMMIT;
PROMPT APEXONE audit storage correction completed successfully.
EXIT
