-- =============================================================================
-- Project        : APEXONE Enterprise Platform
-- Module         : Security
-- Component      : Tables
-- Object Name    : APP_LOGIN_HISTORY
-- Object Type    : TABLE
-- File           : app_login_history.sql
-- Path           : database/modules/security/tables/app_login_history.sql
-- Schema         : APEXONE
-- Version        : 1.1.0-alpha.1
-- Status         : Development
-- -----------------------------------------------------------------------------
-- Author         : Hamdy Fleafel
-- Title          : Enterprise Database Architect
-- Email          : hamdy.fleafel@belcofarms.com
-- WhatsApp       : 0020 1010506080
-- -----------------------------------------------------------------------------
-- Description    : Stores complete login audit trail including success,
--                  failure, IP address and user agent information.
-- -----------------------------------------------------------------------------
-- Created On     : 2026-08-05
-- Last Modified  : 2026-08-05
-- -----------------------------------------------------------------------------
-- Change Log     :
--   2026-08-05  HF  Initial creation.
-- -----------------------------------------------------------------------------
-- Copyright (c) 2026 Hamdy Fleafel. All rights reserved.
-- =============================================================================

PROMPT ============================================================================
PROMPT Creating APP_LOGIN_HISTORY
PROMPT ============================================================================

DECLARE
    l_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO l_exists
      FROM USER_TABLES
     WHERE TABLE_NAME = 'APP_LOGIN_HISTORY';

    IF l_exists = 0 THEN

        EXECUTE IMMEDIATE q'[
            CREATE TABLE APP_LOGIN_HISTORY
            (
                LOGIN_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY,
                USER_ID         NUMBER,
                USERNAME        VARCHAR2(100 CHAR),
                LOGIN_TIME      TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
                IP_ADDRESS      VARCHAR2(64 CHAR),
                USER_AGENT      VARCHAR2(512 CHAR),
                IS_SUCCESS      CHAR(1) DEFAULT 'N' NOT NULL,
                FAILURE_REASON  VARCHAR2(400 CHAR)
            )
                  TABLESPACE APEXONE_AUDIT
        ]';

        DBMS_OUTPUT.PUT_LINE('APP_LOGIN_HISTORY created.');

    ELSE
        DBMS_OUTPUT.PUT_LINE('APP_LOGIN_HISTORY already exists.');
    END IF;

END;
/

COMMIT;

PROMPT Completed.