-- =============================================================================
-- Project        : APEXONE Enterprise Platform
-- Module         : Security
-- Component      : Tables
-- Object Name    : APP_PASSWORD_HISTORY
-- Object Type    : TABLE
-- File           : app_password_history.sql
-- Path           : database/modules/security/tables/app_password_history.sql
-- Schema         : APEXONE
-- Version        : 2.0.0-alpha.1
-- Status         : Development
-- =============================================================================

-- Author         : Hamdy Fleafel
-- Title          : Enterprise Database Architect
-- Email          : hamdy.fleafel@belcofarms.com
-- WhatsApp       : 0020 1010506080
--
-- Description    : Stores historical password hashes and salts used by
--                  application users to prevent password reuse.
--
-- Created On     : 2026-08-05
-- Last Modified  : 2026-08-12
--
-- Change Log     :
--   2026-08-05  HF  Initial creation.
--   2026-08-12  HF  Standardized password history structure.
--   2026-08-12  HF  Added primary key, foreign key and lookup index.
--
-- Copyright (c) 2026 Hamdy Fleafel. All rights reserved.
-- =============================================================================


PROMPT
PROMPT ============================================================================
PROMPT Creating APP_PASSWORD_HISTORY
PROMPT ============================================================================
PROMPT


SET DEFINE OFF
SET SERVEROUTPUT ON
SET VERIFY OFF
SET FEEDBACK ON
SET SQLBLANKLINES ON


DECLARE
    l_exists NUMBER;
BEGIN

    SELECT COUNT(*)
      INTO l_exists
      FROM USER_TABLES
     WHERE TABLE_NAME = 'APP_PASSWORD_HISTORY';


    IF l_exists = 0 THEN

        EXECUTE IMMEDIATE q'[
            CREATE TABLE APP_PASSWORD_HISTORY
            (
                HISTORY_ID
                    NUMBER
                    GENERATED BY DEFAULT AS IDENTITY
                    NOT NULL,

                USER_ID
                    NUMBER(19)
                    NOT NULL,

                PASSWORD_HASH
                    VARCHAR2(2000 CHAR)
                    NOT NULL,

                PASSWORD_SALT
                    VARCHAR2(512 CHAR)
                    NOT NULL,

                CHANGED_AT
                    TIMESTAMP WITH LOCAL TIME ZONE
                    DEFAULT SYSTIMESTAMP
                    NOT NULL,

                CONSTRAINT PK_APP_PASSWORD_HISTORY
                    PRIMARY KEY (HISTORY_ID),

                CONSTRAINT FK_APP_PASSWORD_HISTORY_USER
                    FOREIGN KEY (USER_ID)
                    REFERENCES APP_USERS (USER_ID)
            )
            TABLESPACE APEXONE_DATA
        ]';


        DBMS_OUTPUT.PUT_LINE(
            'APP_PASSWORD_HISTORY created.'
        );


    ELSE

        DBMS_OUTPUT.PUT_LINE(
            'APP_PASSWORD_HISTORY already exists.'
        );

    END IF;

END;
/


PROMPT
PROMPT ============================================================================
PROMPT Creating APP_PASSWORD_HISTORY lookup index
PROMPT ============================================================================
PROMPT


DECLARE
    l_exists NUMBER;
BEGIN

    SELECT COUNT(*)
      INTO l_exists
      FROM USER_INDEXES
     WHERE INDEX_NAME = 'IX_APP_PASSWORD_HISTORY_USER';


    IF l_exists = 0 THEN

        EXECUTE IMMEDIATE q'[
            CREATE INDEX IX_APP_PASSWORD_HISTORY_USER
            ON APP_PASSWORD_HISTORY
            (
                USER_ID,
                CHANGED_AT DESC
            )
            TABLESPACE APEXONE_INDEX
        ]';


        DBMS_OUTPUT.PUT_LINE(
            'IX_APP_PASSWORD_HISTORY_USER created.'
        );


    ELSE

        DBMS_OUTPUT.PUT_LINE(
            'IX_APP_PASSWORD_HISTORY_USER already exists.'
        );

    END IF;

END;
/


PROMPT
PROMPT ============================================================================
PROMPT Applying APP_PASSWORD_HISTORY documentation
PROMPT ============================================================================
PROMPT


COMMENT ON TABLE APP_PASSWORD_HISTORY
IS
'Historical password hashes and salts used to prevent password reuse.';


COMMENT ON COLUMN APP_PASSWORD_HISTORY.HISTORY_ID
IS
'Primary identifier for a password history record.';


COMMENT ON COLUMN APP_PASSWORD_HISTORY.USER_ID
IS
'Application user associated with the historical password.';


COMMENT ON COLUMN APP_PASSWORD_HISTORY.PASSWORD_HASH
IS
'SHA-256 password hash generated by PKG_SECURITY_HASH.';


COMMENT ON COLUMN APP_PASSWORD_HISTORY.PASSWORD_SALT
IS
'Random password salt associated with PASSWORD_HASH.';


COMMENT ON COLUMN APP_PASSWORD_HISTORY.CHANGED_AT
IS
'Timestamp when the password was stored in password history.';


COMMIT;


PROMPT
PROMPT ============================================================================
PROMPT APP_PASSWORD_HISTORY installation completed.
PROMPT ============================================================================
PROMPT