-- APEXONE Identity Session Management
CREATE OR REPLACE PACKAGE BODY PKG_SESSION
IS
    c_session_minutes CONSTANT PLS_INTEGER := 30;

    FUNCTION create_session(p_user_id IN APP_SESSIONS.USER_ID%TYPE, p_ip_address IN APP_SESSIONS.IP_ADDRESS%TYPE DEFAULT NULL, p_user_agent IN APP_SESSIONS.USER_AGENT%TYPE DEFAULT NULL) RETURN VARCHAR2
    IS l_token APP_SESSIONS.SESSION_TOKEN%TYPE;
    BEGIN
        l_token := LOWER(RAWTOHEX(SYS_GUID())) || LOWER(RAWTOHEX(SYS_GUID()));
        INSERT INTO APP_SESSIONS(USER_ID,SESSION_TOKEN,EXPIRES_AT,LAST_ACTIVITY,IP_ADDRESS,USER_AGENT,IS_REVOKED)
        VALUES(p_user_id,l_token,SYSTIMESTAMP + NUMTODSINTERVAL(c_session_minutes,'MINUTE'),SYSTIMESTAMP,p_ip_address,p_user_agent,'N');
        RETURN l_token;
    END;

    FUNCTION validate_session(p_session_token IN APP_SESSIONS.SESSION_TOKEN%TYPE) RETURN NUMBER
    IS l_user_id APP_SESSIONS.USER_ID%TYPE;
    BEGIN
        SELECT USER_ID INTO l_user_id FROM APP_SESSIONS
         WHERE SESSION_TOKEN=p_session_token AND IS_REVOKED='N' AND EXPIRES_AT>SYSTIMESTAMP;
        UPDATE APP_SESSIONS SET LAST_ACTIVITY=SYSTIMESTAMP WHERE SESSION_TOKEN=p_session_token;
        RETURN l_user_id;
    EXCEPTION WHEN NO_DATA_FOUND THEN RETURN NULL;
    END;

    PROCEDURE revoke_session(p_session_token IN APP_SESSIONS.SESSION_TOKEN%TYPE) IS
    BEGIN
        UPDATE APP_SESSIONS SET IS_REVOKED='Y',LAST_ACTIVITY=SYSTIMESTAMP
         WHERE SESSION_TOKEN=p_session_token AND IS_REVOKED='N';
    END;

    PROCEDURE revoke_all_user_sessions(p_user_id IN APP_SESSIONS.USER_ID%TYPE) IS
    BEGIN
        UPDATE APP_SESSIONS SET IS_REVOKED='Y',LAST_ACTIVITY=SYSTIMESTAMP
         WHERE USER_ID=p_user_id AND IS_REVOKED='N';
    END;
END PKG_SESSION;
/
