-- =============================================================================
-- Project        : APEXONE Enterprise Platform
-- Module         : Identity
-- Component      : Tables
-- Object Name    : APP_USER_ROLES
-- Object Type    : TABLE
-- File           : app_user_roles.sql
-- Path           : database/modules/identity/tables/app_user_roles.sql
-- Schema         : APEXONE
-- Version        : 1.3.0-alpha.1
-- Status         : Development
-- -----------------------------------------------------------------------------
-- Author         : Hamdy Fleafel
-- Title          : Enterprise Database Architect
-- Email          : hamdy.fleafel@belcofarms.com
-- WhatsApp       : 0020 1010506080
-- -----------------------------------------------------------------------------
-- Description    : Maps users to roles (many-to-many relationship).
-- -----------------------------------------------------------------------------
-- Created On     : 2026-08-05
-- Last Modified  : 2026-08-05
-- -----------------------------------------------------------------------------
-- Change Log     :
--   2026-08-05  HF  Initial creation.
-- -----------------------------------------------------------------------------
-- Copyright (c) 2026 Hamdy Fleafel. All rights reserved.
-- =============================================================================

PROMPT ============================================================================
PROMPT Creating TABLE APP_USER_ROLES
PROMPT ============================================================================

DECLARE
    l_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO l_exists
      FROM USER_TABLES
     WHERE TABLE_NAME = 'APP_USER_ROLES';

    IF l_exists = 0 THEN

        EXECUTE IMMEDIATE q'[
            CREATE TABLE APP_USER_ROLES
            (
                USER_ROLE_ID NUMBER
                              GENERATED BY DEFAULT AS IDENTITY
                              NOT NULL,

                USER_ID      NUMBER NOT NULL,
                ROLE_ID      NUMBER NOT NULL,

                CREATED_AT   TIMESTAMP WITH LOCAL TIME ZONE
                             DEFAULT SYSTIMESTAMP NOT NULL,

                CREATED_BY   VARCHAR2(128 CHAR)
                             DEFAULT USER NOT NULL
            )
                        TABLESPACE APEXONE_DATA
        ]';

        DBMS_OUTPUT.PUT_LINE('APP_USER_ROLES created.');

    ELSE
        DBMS_OUTPUT.PUT_LINE('APP_USER_ROLES already exists.');
    END IF;

END;
/

COMMIT;

PROMPT Completed.