-- =============================================================================
-- Project        : APEXONE Enterprise Platform
-- Module         : Identity
-- Component      : Tables
-- Object Name    : APP_PERMISSIONS
-- Object Type    : TABLE
-- File           : app_permissions.sql
-- Path           : database/modules/identity/tables/app_permissions.sql
-- Schema         : APEXONE
-- Version        : 1.1.0-alpha.1
-- Status         : Development
-- -----------------------------------------------------------------------------
-- Author         : Hamdy Fleafel
-- Title          : Enterprise Database Architect
-- Email          : hamdy.fleafel@belcofarms.com
-- WhatsApp       : 0020 1010506080
-- -----------------------------------------------------------------------------
-- Description    : Stores platform permissions used by the RBAC model.
-- -----------------------------------------------------------------------------
-- Created On     : 2026-08-05
-- Last Modified  : 2026-08-05
-- -----------------------------------------------------------------------------
-- Change Log     :
--   2026-08-05  HF  Initial creation.
-- -----------------------------------------------------------------------------
-- Copyright (c) 2026 Hamdy Fleafel. All rights reserved.
-- =============================================================================

PROMPT ============================================================================
PROMPT Creating APP_PERMISSIONS
PROMPT ============================================================================

SET DEFINE OFF
SET SERVEROUTPUT ON
SET VERIFY OFF
SET FEEDBACK ON

DECLARE
    l_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO l_exists
      FROM USER_TABLES
     WHERE TABLE_NAME = 'APP_PERMISSIONS';

    IF l_exists = 0 THEN

        EXECUTE IMMEDIATE q'[
            CREATE TABLE APP_PERMISSIONS
            (
                PERMISSION_ID    NUMBER
                                  GENERATED BY DEFAULT AS IDENTITY
                                  NOT NULL,

                PERMISSION_CODE  VARCHAR2(150 CHAR)
                                  NOT NULL,

                PERMISSION_NAME  VARCHAR2(200 CHAR)
                                  NOT NULL,

                DESCRIPTION      VARCHAR2(1000 CHAR),

                STATUS           VARCHAR2(20 CHAR)
                                  DEFAULT 'ACTIVE'
                                  NOT NULL,

                IS_DELETED       CHAR(1 CHAR)
                                  DEFAULT 'N'
                                  NOT NULL,

                CREATED_AT       TIMESTAMP WITH LOCAL TIME ZONE
                                  DEFAULT SYSTIMESTAMP
                                  NOT NULL,

                CREATED_BY       VARCHAR2(128 CHAR)
                                  DEFAULT USER
                                  NOT NULL,

                UPDATED_AT       TIMESTAMP WITH LOCAL TIME ZONE,

                UPDATED_BY       VARCHAR2(128 CHAR)
            )
                            TABLESPACE APEXONE_DATA
        ]';

        DBMS_OUTPUT.PUT_LINE(
            'APP_PERMISSIONS created.'
        );

    ELSE

        DBMS_OUTPUT.PUT_LINE(
            'APP_PERMISSIONS already exists.'
        );

    END IF;
END;
/

COMMIT;

PROMPT Completed.