-- =============================================================================
-- Project        : APEXONE Enterprise Platform
-- Module         : Identity
-- Component      : Tables
-- Object Name    : APP_ROLE_PERMISSIONS
-- Object Type    : TABLE
-- File           : app_role_permissions.sql
-- Path           : database/modules/identity/tables/app_role_permissions.sql
-- Schema         : APEXONE
-- Version        : 1.1.0-alpha.1
-- Status         : Development
-- -----------------------------------------------------------------------------
-- Author         : Hamdy Fleafel
-- Title          : Enterprise Database Architect
-- Email          : hamdy.fleafel@belcofarms.com
-- WhatsApp       : 0020 1010506080
-- -----------------------------------------------------------------------------
-- Description    : Maps roles to permissions (RBAC core mapping table).
-- -----------------------------------------------------------------------------
-- Created On     : 2026-08-05
-- Last Modified  : 2026-08-05
-- -----------------------------------------------------------------------------
-- Change Log     :
--   2026-08-05  HF  Initial creation.
-- -----------------------------------------------------------------------------
-- Copyright (c) 2026 Hamdy Fleafel. All rights reserved.
-- =============================================================================

PROMPT Creating APP_ROLE_PERMISSIONS...

DECLARE
    l_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_exists
    FROM USER_TABLES
    WHERE TABLE_NAME = 'APP_ROLE_PERMISSIONS';

    IF l_exists = 0 THEN

        EXECUTE IMMEDIATE q'[
            CREATE TABLE APP_ROLE_PERMISSIONS
            (
                ROLE_PERMISSION_ID NUMBER
                    GENERATED BY DEFAULT AS IDENTITY,

                ROLE_ID        NUMBER NOT NULL,
                PERMISSION_ID  NUMBER NOT NULL,

                CREATED_AT     TIMESTAMP WITH LOCAL TIME ZONE
                               DEFAULT SYSTIMESTAMP NOT NULL,

                CREATED_BY     VARCHAR2(128 CHAR)
                               DEFAULT USER NOT NULL
            )
                         TABLESPACE APEXONE_DATA
        ]';

    END IF;
END;
/

COMMIT;