-- =============================================================================
-- Project        : APEXONE Enterprise Platform
-- Module         : Identity
-- Component      : Tables
-- Object Name    : APP_ROLES
-- Object Type    : TABLE
-- File           : app_roles.sql
-- Path           : database/modules/identity/tables/app_roles.sql
-- Schema         : APEXONE
-- Version        : 1.1.0-alpha.1
-- Status         : Development
-- -----------------------------------------------------------------------------
-- Author         : Hamdy Fleafel
-- Title          : Enterprise Database Architect
-- Email          : hamdy.fleafel@belcofarms.com
-- WhatsApp       : +20 1010506080
-- -----------------------------------------------------------------------------
-- Description    : Stores platform roles used in RBAC model.
-- -----------------------------------------------------------------------------
-- Created On     : 2026-08-05
-- Last Modified  : 2026-08-05
-- -----------------------------------------------------------------------------
-- Change Log     :
--   2026-08-05  HF  Initial creation.
-- -----------------------------------------------------------------------------
-- Copyright (c) 2026 Hamdy Fleafel. All rights reserved.
-- =============================================================================

PROMPT Creating table APP_ROLES...

DECLARE
    l_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_exists
    FROM USER_TABLES
    WHERE TABLE_NAME = 'APP_ROLES';

    IF l_exists = 0 THEN

        EXECUTE IMMEDIATE q'[
            CREATE TABLE APP_ROLES
            (
                ROLE_ID    NUMBER GENERATED BY DEFAULT AS IDENTITY,
                ROLE_CODE  VARCHAR2(100 CHAR) NOT NULL,
                ROLE_NAME  VARCHAR2(200 CHAR) NOT NULL,
                CREATED_AT TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
                CREATED_BY VARCHAR2(128 CHAR) DEFAULT USER NOT NULL
            )
                         TABLESPACE APEXONE_DATA
        ]';

    END IF;
END;
/

COMMIT;