-- =============================================================================
-- Project        : APEXONE Enterprise Platform
-- Module         : Identity
-- Component      : Tables
-- Object Name    : APP_SESSIONS
-- Object Type    : TABLE
-- File           : app_sessions.sql
-- Path           : database/modules/identity/tables/app_sessions.sql
-- Schema         : APEXONE
-- Version        : 1.5.0-alpha.1
-- Status         : Development
-- =============================================================================
-- Author         : Hamdy Fleafel
-- Title          : Enterprise Database Architect
-- Email          : hamdy.fleafel@belcofarms.com
-- WhatsApp       : 0020 1010506080
-- =============================================================================
-- Description    : Stores authentication sessions and tokens.
-- =============================================================================
-- Created On     : 2026-08-05
-- Last Modified  : 2026-08-10
-- =============================================================================
-- Change Log     :
--   2026-08-05  HF  Initial creation.
--   2026-08-10  HF  Simplified dynamic SQL execution to avoid quoted-string
--                   parsing errors during SQL*Plus installation.
-- =============================================================================
-- Copyright (c) 2026 Hamdy Fleafel. All rights reserved.
-- =============================================================================

SET DEFINE OFF
SET VERIFY OFF
SET FEEDBACK ON
SET SERVEROUTPUT ON

PROMPT
PROMPT =============================================================================
PROMPT Creating APP_SESSIONS
PROMPT =============================================================================

DECLARE
    l_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO l_exists
      FROM USER_TABLES
     WHERE TABLE_NAME = 'APP_SESSIONS';

    IF l_exists = 0 THEN

        EXECUTE IMMEDIATE
            'CREATE TABLE APP_SESSIONS
             (
                 SESSION_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY,
                 USER_ID         NUMBER NOT NULL,
                 SESSION_TOKEN   VARCHAR2(256 CHAR) NOT NULL,
                 CREATED_AT      TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
                 EXPIRES_AT      TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
                 LAST_ACTIVITY   TIMESTAMP WITH LOCAL TIME ZONE,
                 IP_ADDRESS      VARCHAR2(64 CHAR),
                 USER_AGENT      VARCHAR2(512 CHAR),
                 IS_REVOKED      CHAR(1) DEFAULT ''N'' NOT NULL
             )
             TABLESPACE APEXONE_DATA';

        DBMS_OUTPUT.PUT_LINE('APP_SESSIONS created successfully.');

    ELSE

        DBMS_OUTPUT.PUT_LINE('APP_SESSIONS already exists.');

    END IF;
END;
/

COMMIT;

PROMPT
PROMPT =============================================================================
PROMPT APP_SESSIONS TABLE INSTALLATION COMPLETED
PROMPT =============================================================================