-- =============================================================================
-- Project        : APEXONE Enterprise Platform
-- Module         : Identity
-- Component      : Tables
-- Object Name    : APP_LOGIN_ATTEMPTS
-- Object Type    : TABLE
-- File           : app_login_attempts.sql
-- Path           : database/modules/identity/tables/app_login_attempts.sql
-- Schema         : APEXONE
-- Version        : 1.6.0-alpha.1
-- Status         : Development
-- -----------------------------------------------------------------------------
-- Author         : Hamdy Fleafel
-- Title          : Enterprise Database Architect
-- Email          : hamdy.fleafel@belcofarms.com
-- WhatsApp       : 0020 1010506080
-- -----------------------------------------------------------------------------
-- Description    : Tracks failed login attempts for brute force protection.
-- -----------------------------------------------------------------------------
-- Created On     : 2026-08-05
-- Last Modified  : 2026-08-05
-- -----------------------------------------------------------------------------
-- Change Log     :
--   2026-08-05  HF  Initial creation.
-- -----------------------------------------------------------------------------
-- Copyright (c) 2026 Hamdy Fleafel. All rights reserved.
-- =============================================================================

PROMPT Creating APP_LOGIN_ATTEMPTS...

DECLARE
    l_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO l_exists
      FROM USER_TABLES
     WHERE TABLE_NAME = 'APP_LOGIN_ATTEMPTS';

    IF l_exists = 0 THEN

        EXECUTE IMMEDIATE q'[
            CREATE TABLE APP_LOGIN_ATTEMPTS
            (
                ATTEMPT_ID     NUMBER GENERATED BY DEFAULT AS IDENTITY,
                USERNAME       VARCHAR2(100 CHAR) NOT NULL,
                IP_ADDRESS     VARCHAR2(64 CHAR),
                ATTEMPT_TIME   TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
                IS_SUCCESS     CHAR(1) DEFAULT 'N' NOT NULL
            )
                          TABLESPACE APEXONE_DATA
        ]';

    END IF;
END;
/

COMMIT;
PROMPT Completed.