-- =====================================================
-- APEXONE Enterprise Platform
-- Security Role
-- Script: create_apexone_app_role.sql
-- Version: V001
-- =====================================================

CREATE ROLE APEXONE_APP_ROLE;

GRANT CREATE SESSION TO APEXONE_APP_ROLE;
GRANT CREATE TABLE TO APEXONE_APP_ROLE;
GRANT CREATE VIEW TO APEXONE_APP_ROLE;
GRANT CREATE SEQUENCE TO APEXONE_APP_ROLE;
GRANT CREATE PROCEDURE TO APEXONE_APP_ROLE;
GRANT CREATE TRIGGER TO APEXONE_APP_ROLE;
GRANT CREATE TYPE TO APEXONE_APP_ROLE;

GRANT APEXONE_APP_ROLE TO APEXONE;