-- APEXONE Enterprise Platform - Create / Normalize Application Schema
ALTER SESSION SET CONTAINER = FREEPDB1;
SET DEFINE OFF
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET VERIFY OFF

DECLARE
    l_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_exists FROM DBA_USERS WHERE USERNAME = 'APEXONE';
    IF l_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE USER APEXONE IDENTIFIED BY Apex123#
            DEFAULT TABLESPACE APEXONE_DATA
            TEMPORARY TABLESPACE TEMP
            QUOTA UNLIMITED ON APEXONE_DATA
            QUOTA UNLIMITED ON APEXONE_INDEX
            QUOTA UNLIMITED ON APEXONE_AUDIT
        ]';
        DBMS_OUTPUT.PUT_LINE('APEXONE user created.');
    ELSE
        EXECUTE IMMEDIATE 'ALTER USER APEXONE DEFAULT TABLESPACE APEXONE_DATA';
        EXECUTE IMMEDIATE 'ALTER USER APEXONE TEMPORARY TABLESPACE TEMP';
        EXECUTE IMMEDIATE 'ALTER USER APEXONE QUOTA UNLIMITED ON APEXONE_DATA';
        EXECUTE IMMEDIATE 'ALTER USER APEXONE QUOTA UNLIMITED ON APEXONE_INDEX';
        EXECUTE IMMEDIATE 'ALTER USER APEXONE QUOTA UNLIMITED ON APEXONE_AUDIT';
        EXECUTE IMMEDIATE 'ALTER USER APEXONE QUOTA 0 ON USERS';
        DBMS_OUTPUT.PUT_LINE('APEXONE user already exists; configuration normalized.');
    END IF;
END;
/

GRANT CREATE SESSION TO APEXONE;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE,
      CREATE TRIGGER, CREATE TYPE, CREATE SYNONYM TO APEXONE;
COMMIT;
PROMPT APEXONE user configuration normalized successfully.
EXIT
