-- =============================================================================
-- Project : APEXONE Enterprise Platform
-- Module : Core
-- Component : APP_FILE_METADATA Table
-- Path : database\modules\core\tables\app_file_metadata.sql
-- Schema : APEXONE
-- Version : 1.3.0-alpha.1
-- Status : Development
-- -----------------------------------------------------------------------------
-- Author : Hamdy Fleafel
-- Title : Enterprise Database Architect
-- Email : hamdy.fleafel@belcofarms.com
-- WhatsApp : 0020 1010506080
-- -----------------------------------------------------------------------------
-- Description : Metadata registry for files stored outside the database
--               under the APEX_FILES Oracle DIRECTORY.
-- -----------------------------------------------------------------------------
-- Created On : 2026-08-08
-- Last Modified : 2026-08-08
-- -----------------------------------------------------------------------------
-- Change Log :
-- 2026-08-08 HF Initial creation.
-- -----------------------------------------------------------------------------
-- Copyright (c) 2026 Hamdy Fleafel. All rights reserved.
-- =============================================================================
-- =============================================================================
-- Project        : APEXONE Enterprise Platform
-- Module         : Core
-- Component      : File Metadata
-- Object Name    : APP_FILE_METADATA
-- Object Type    : TABLE
-- =============================================================================
DECLARE
    l_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO l_count
      FROM USER_TABLES
     WHERE TABLE_NAME = 'APP_FILE_METADATA';

    IF l_count = 0 THEN

        EXECUTE IMMEDIATE '
            CREATE TABLE APP_FILE_METADATA
            (
                FILE_ID             NUMBER GENERATED BY DEFAULT AS IDENTITY,
                FILE_NAME           VARCHAR2(255 CHAR) NOT NULL,
                RELATIVE_PATH       VARCHAR2(1000 CHAR) NOT NULL,
                FILE_EXTENSION      VARCHAR2(50 CHAR),
                MIME_TYPE           VARCHAR2(255 CHAR),
                FILE_SIZE_BYTES     NUMBER(19, 0),
                CHECKSUM_SHA256     VARCHAR2(64 CHAR),
                FILE_STATUS         VARCHAR2(30 CHAR) DEFAULT ''RECEIVED'' NOT NULL,
                CREATED_AT          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                PROCESSED_AT        TIMESTAMP(6),
                ERROR_MESSAGE       VARCHAR2(4000 CHAR)
            )
            TABLESPACE APEXONE_DATA
        ';

        DBMS_OUTPUT.PUT_LINE(
            'APP_FILE_METADATA created successfully.'
        );

    ELSE

        DBMS_OUTPUT.PUT_LINE(
            'APP_FILE_METADATA already exists. Skipping creation.'
        );

    END IF;
END;
/
