-- =============================================================================
-- Project        : APEXONE Enterprise Platform
-- Module         : Core
-- Component      : Installation Logging
-- Object Name    : APP_INSTALL_LOG
-- Object Type    : TABLE
-- File           : app_install_log.sql
-- Schema         : APEXONE
-- Description    : Stores module installation execution history.
-- Author         : Hamdy Fleafel
-- Version        : 1.0.0-alpha.3
-- Database       : Oracle AI Database 26ai
-- =============================================================================


PROMPT ============================================================================
PROMPT Creating APP_INSTALL_LOG
PROMPT ============================================================================


SET DEFINE OFF
SET SERVEROUTPUT ON
SET VERIFY OFF
SET FEEDBACK ON


DECLARE
    l_exists NUMBER;
BEGIN

    SELECT COUNT(*)
    INTO l_exists
    FROM USER_TABLES
    WHERE TABLE_NAME = 'APP_INSTALL_LOG';


    IF l_exists = 0 THEN

        EXECUTE IMMEDIATE q'[
            CREATE TABLE APP_INSTALL_LOG
            (
                INSTALL_ID      NUMBER
                                GENERATED BY DEFAULT AS IDENTITY
                                CONSTRAINT PK_APP_INSTALL_LOG
                                PRIMARY KEY,

                MODULE_NAME     VARCHAR2(100 CHAR) NOT NULL,
                MODULE_VERSION  VARCHAR2(30 CHAR)  NOT NULL,

                STARTED_AT      TIMESTAMP WITH LOCAL TIME ZONE
                                DEFAULT SYSTIMESTAMP NOT NULL,

                COMPLETED_AT    TIMESTAMP WITH LOCAL TIME ZONE,

                INSTALLED_BY    VARCHAR2(128 CHAR)
                                DEFAULT USER NOT NULL,

                STATUS          VARCHAR2(20 CHAR) NOT NULL,

                ERROR_MESSAGE   VARCHAR2(2000 CHAR),

                CONSTRAINT CHK_APP_INSTALL_LOG_STATUS
                    CHECK
                    (
                        STATUS IN
                        (
                            'RUNNING',
                            'SUCCESS',
                            'FAILED'
                        )
                    )
            )
                TABLESPACE APEXONE_DATA
        ]';

        DBMS_OUTPUT.PUT_LINE(
            'APP_INSTALL_LOG created.'
        );

    ELSE

        DBMS_OUTPUT.PUT_LINE(
            'APP_INSTALL_LOG already exists.'
        );

    END IF;

END;
/
-------------------------------------------------------------------------------

COMMENT ON TABLE APP_INSTALL_LOG
IS 'Module installation execution history.';


COMMENT ON COLUMN APP_INSTALL_LOG.INSTALL_ID
IS 'Primary key (identity).';


COMMENT ON COLUMN APP_INSTALL_LOG.MODULE_NAME
IS 'Module name (e.g., CORE, IDENTITY, SECURITY).';


COMMENT ON COLUMN APP_INSTALL_LOG.MODULE_VERSION
IS 'Installed module version.';


COMMENT ON COLUMN APP_INSTALL_LOG.STARTED_AT
IS 'Installation start timestamp.';


COMMENT ON COLUMN APP_INSTALL_LOG.COMPLETED_AT
IS 'Installation completion timestamp.';


COMMENT ON COLUMN APP_INSTALL_LOG.INSTALLED_BY
IS 'Database user executing installation.';


COMMENT ON COLUMN APP_INSTALL_LOG.STATUS
IS 'Installation status.';


COMMENT ON COLUMN APP_INSTALL_LOG.ERROR_MESSAGE
IS 'Error message if installation failed.';


-------------------------------------------------------------------------------
-- Index on STATUS
-------------------------------------------------------------------------------

DECLARE
    l_exists NUMBER;
BEGIN

    SELECT COUNT(*)
    INTO l_exists
    FROM USER_INDEXES
    WHERE INDEX_NAME = 'IDX_APP_INSTALL_LOG_STATUS';


    IF l_exists = 0 THEN

        EXECUTE IMMEDIATE '
            CREATE INDEX IDX_APP_INSTALL_LOG_STATUS
            ON APP_INSTALL_LOG (STATUS)
            TABLESPACE APEXONE_INDEX
        ';

        DBMS_OUTPUT.PUT_LINE(
            'IDX_APP_INSTALL_LOG_STATUS created.'
        );

    ELSE

        DBMS_OUTPUT.PUT_LINE(
            'IDX_APP_INSTALL_LOG_STATUS already exists.'
        );

    END IF;

END;
/
-------------------------------------------------------------------------------
-- Index on STARTED_AT
-------------------------------------------------------------------------------

DECLARE
    l_exists NUMBER;
BEGIN

    SELECT COUNT(*)
    INTO l_exists
    FROM USER_INDEXES
    WHERE INDEX_NAME = 'IDX_APP_INSTALL_LOG_DATE';


    IF l_exists = 0 THEN

        EXECUTE IMMEDIATE '
            CREATE INDEX IDX_APP_INSTALL_LOG_DATE
            ON APP_INSTALL_LOG (STARTED_AT)
            TABLESPACE APEXONE_INDEX
        ';

        DBMS_OUTPUT.PUT_LINE(
            'IDX_APP_INSTALL_LOG_DATE created.'
        );

    ELSE

        DBMS_OUTPUT.PUT_LINE(
            'IDX_APP_INSTALL_LOG_DATE already exists.'
        );

    END IF;

END;
/
-------------------------------------------------------------------------------

COMMIT;

PROMPT Completed.

