/*====================================================================
  APEXONE Enterprise Platform

  File Name    : app_notification_templates.sql
  Module       : Notification Framework
  Object Type  : TABLE
  Object Name  : APP_NOTIFICATION_TEMPLATES

  Purpose:
  Stores notification templates.

  Version      : 1.0.0-alpha.4
====================================================================*/

PROMPT ============================================================================
PROMPT Creating TABLE APP_NOTIFICATION_TEMPLATES
PROMPT ============================================================================

SET DEFINE OFF
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET VERIFY OFF

DECLARE
    l_exists NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO l_exists
    FROM user_tables
    WHERE table_name='APP_NOTIFICATION_TEMPLATES';

    IF l_exists=0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE app_notification_templates
            (
                template_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                template_code VARCHAR2(100 CHAR) NOT NULL,
                template_name VARCHAR2(200 CHAR) NOT NULL,
                subject VARCHAR2(500 CHAR),
                body_text CLOB,
                active_flag VARCHAR2(1 CHAR) DEFAULT 'Y' NOT NULL,
                created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
            )
              TABLESPACE APEXONE_DATA
        ]';

        DBMS_OUTPUT.PUT_LINE('APP_NOTIFICATION_TEMPLATES created.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('APP_NOTIFICATION_TEMPLATES already exists.');
    END IF;
END;
/

COMMENT ON TABLE app_notification_templates IS 'Notification templates.';
COMMENT ON COLUMN app_notification_templates.template_id IS 'Primary key.';
COMMENT ON COLUMN app_notification_templates.template_code IS 'Unique template code.';
COMMENT ON COLUMN app_notification_templates.template_name IS 'Template name.';
COMMENT ON COLUMN app_notification_templates.subject IS 'Notification subject.';
COMMENT ON COLUMN app_notification_templates.body_text IS 'Template body.';
COMMENT ON COLUMN app_notification_templates.active_flag IS 'Active flag.';
COMMENT ON COLUMN app_notification_templates.created_date IS 'Creation timestamp.';


PROMPT Completed.
