/*====================================================================
  APEXONE Enterprise Platform

  File Name    : app_notifications.sql
  Module       : Notification Framework
  Object Type  : TABLE
  Object Name  : APP_NOTIFICATIONS

  Purpose:
  Stores notification transactions.

  Version      : 1.0.0-alpha.4
====================================================================*/

PROMPT ============================================================================
PROMPT Creating TABLE APP_NOTIFICATIONS
PROMPT ============================================================================

SET DEFINE OFF
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET VERIFY OFF

DECLARE
    l_exists NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO l_exists
    FROM user_tables
    WHERE table_name='APP_NOTIFICATIONS';

    IF l_exists=0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE app_notifications
            (
                notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                template_id NUMBER NOT NULL,
                recipient VARCHAR2(200 CHAR),
                notification_status VARCHAR2(30 CHAR) DEFAULT 'NEW',
                message_body CLOB,
                sent_date TIMESTAMP,
                created_date TIMESTAMP DEFAULT SYSTIMESTAMP,
                CONSTRAINT app_notifications_pk
                    PRIMARY KEY(notification_id)
            )
               TABLESPACE APEXONE_DATA
        ]';

        DBMS_OUTPUT.PUT_LINE('APP_NOTIFICATIONS created.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('APP_NOTIFICATIONS already exists.');
    END IF;
END;
/

COMMENT ON TABLE app_notifications IS 'Notification transactions.';
COMMENT ON COLUMN app_notifications.notification_id IS 'Primary key.';
COMMENT ON COLUMN app_notifications.template_id IS 'Notification template.';
COMMENT ON COLUMN app_notifications.recipient IS 'Recipient.';
COMMENT ON COLUMN app_notifications.notification_status IS 'Notification status.';
COMMENT ON COLUMN app_notifications.message_body IS 'Notification body.';
COMMENT ON COLUMN app_notifications.sent_date IS 'Sent timestamp.';
COMMENT ON COLUMN app_notifications.created_date IS 'Creation timestamp.';

DECLARE
    l_exists NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO l_exists
    FROM user_indexes
    WHERE index_name='IDX_APP_NOTIFICATIONS_STATUS';

    IF l_exists=0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX IDX_APP_NOTIFICATIONS_STATUS ON APP_NOTIFICATIONS(NOTIFICATION_STATUS) TABLESPACE APEXONE_INDEX';
        DBMS_OUTPUT.PUT_LINE('IDX_APP_NOTIFICATIONS_STATUS created.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('IDX_APP_NOTIFICATIONS_STATUS already exists.');
    END IF;
END;
/

DECLARE
    l_exists NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO l_exists
    FROM user_indexes
    WHERE index_name='IDX_APP_NOTIFICATIONS_TEMPLATE';

    IF l_exists=0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX IDX_APP_NOTIFICATIONS_TEMPLATE ON APP_NOTIFICATIONS(TEMPLATE_ID) TABLESPACE APEXONE_INDEX';
        DBMS_OUTPUT.PUT_LINE('IDX_APP_NOTIFICATIONS_TEMPLATE created.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('IDX_APP_NOTIFICATIONS_TEMPLATE already exists.');
    END IF;
END;
/

COMMIT;

PROMPT Completed.
