-- =============================================================================
-- Project        : APEXONE Enterprise Platform
-- Module         : Configuration Framework
-- Component      : Configuration Tables
-- Object Name    : APP_CONFIG
-- Object Type    : TABLE
-- File           : app_config.sql
-- Schema         : APEXONE
-- Description    : Stores application configuration values.
-- Author         : Hamdy Fleafel
-- Version        : 1.0.0-alpha.3
-- =============================================================================

PROMPT ============================================================================
PROMPT Creating TABLE APP_CONFIG
PROMPT ============================================================================

SET DEFINE OFF
SET SERVEROUTPUT ON
SET VERIFY OFF
SET FEEDBACK ON

DECLARE
    l_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO l_exists
      FROM USER_TABLES
     WHERE TABLE_NAME='APP_CONFIG';

    IF l_exists=0 THEN

        EXECUTE IMMEDIATE q'[
CREATE TABLE APP_CONFIG
(
    CONFIG_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    CONFIG_KEY VARCHAR2(200 CHAR) NOT NULL,
    CONFIG_VALUE VARCHAR2(4000 CHAR),
    CONFIG_GROUP VARCHAR2(100 CHAR),
    DESCRIPTION VARCHAR2(500 CHAR),
    ACTIVE_FLAG VARCHAR2(1 CHAR) DEFAULT 'Y' NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_DATE TIMESTAMP
)
  TABLESPACE APEXONE_DATA
]';

        DBMS_OUTPUT.PUT_LINE('APP_CONFIG created.');

    ELSE

        DBMS_OUTPUT.PUT_LINE('APP_CONFIG already exists.');

    END IF;
END;
/

COMMENT ON TABLE APP_CONFIG IS 'Stores application configuration values.';
COMMENT ON COLUMN APP_CONFIG.CONFIG_ID IS 'Configuration identifier.';
COMMENT ON COLUMN APP_CONFIG.CONFIG_KEY IS 'Configuration key.';
COMMENT ON COLUMN APP_CONFIG.CONFIG_VALUE IS 'Configuration value.';
COMMENT ON COLUMN APP_CONFIG.CONFIG_GROUP IS 'Configuration group code.';
COMMENT ON COLUMN APP_CONFIG.DESCRIPTION IS 'Configuration description.';
COMMENT ON COLUMN APP_CONFIG.ACTIVE_FLAG IS 'Active flag.';
COMMENT ON COLUMN APP_CONFIG.CREATED_DATE IS 'Creation timestamp.';
COMMENT ON COLUMN APP_CONFIG.UPDATED_DATE IS 'Last update timestamp.';

COMMIT;

PROMPT Completed.