-- =============================================================================
-- Project        : APEXONE Enterprise Platform
-- Module         : Workflow Framework
-- Component      : Tables
-- Object Name    : APP_WORKFLOW_DEFINITIONS
-- Object Type    : TABLE
-- File           : app_workflow_definitions.sql
-- Schema         : APEXONE
-- Description    : Stores workflow definitions.
-- Author         : Hamdy Fleafel
-- Version        : 1.0.0-alpha.4
-- =============================================================================

PROMPT ============================================================================
PROMPT Creating TABLE APP_WORKFLOW_DEFINITIONS
PROMPT ============================================================================

SET DEFINE OFF
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET VERIFY OFF

DECLARE
    l_exists NUMBER;
BEGIN

    SELECT COUNT(*)
      INTO l_exists
      FROM USER_TABLES
     WHERE TABLE_NAME='APP_WORKFLOW_DEFINITIONS';

    IF l_exists=0 THEN

        EXECUTE IMMEDIATE q'[
CREATE TABLE APP_WORKFLOW_DEFINITIONS
(
    WORKFLOW_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    WORKFLOW_CODE    VARCHAR2(100 CHAR) NOT NULL,
    WORKFLOW_NAME    VARCHAR2(200 CHAR) NOT NULL,
    DESCRIPTION      VARCHAR2(500 CHAR),
    ACTIVE_FLAG      VARCHAR2(1 CHAR) DEFAULT 'Y' NOT NULL,
    CREATED_DATE     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_APP_WORKFLOW_DEF_ACTIVE
        CHECK (ACTIVE_FLAG IN ('Y','N'))
)
]';

        DBMS_OUTPUT.PUT_LINE('APP_WORKFLOW_DEFINITIONS created.');

    ELSE

        DBMS_OUTPUT.PUT_LINE('APP_WORKFLOW_DEFINITIONS already exists.');

    END IF;

END;
/

COMMENT ON TABLE APP_WORKFLOW_DEFINITIONS IS 'Workflow definitions.';
COMMENT ON COLUMN APP_WORKFLOW_DEFINITIONS.WORKFLOW_ID IS 'Primary key.';
COMMENT ON COLUMN APP_WORKFLOW_DEFINITIONS.WORKFLOW_CODE IS 'Workflow code.';
COMMENT ON COLUMN APP_WORKFLOW_DEFINITIONS.WORKFLOW_NAME IS 'Workflow name.';
COMMENT ON COLUMN APP_WORKFLOW_DEFINITIONS.DESCRIPTION IS 'Workflow description.';
COMMENT ON COLUMN APP_WORKFLOW_DEFINITIONS.ACTIVE_FLAG IS 'Active flag.';
COMMENT ON COLUMN APP_WORKFLOW_DEFINITIONS.CREATED_DATE IS 'Creation timestamp.';

COMMIT;

PROMPT Completed.
