-- =============================================================================
-- Project        : APEXONE Enterprise Platform
-- Module         : Workflow Framework
-- Component      : Tables
-- Object Name    : APP_WORKFLOW_TASKS
-- Object Type    : TABLE
-- File           : app_workflow_tasks.sql
-- Schema         : APEXONE
-- Description    : Stores workflow tasks.
-- Author         : Hamdy Fleafel
-- Version        : 1.0.0-alpha.4
-- =============================================================================

PROMPT ============================================================================
PROMPT Creating TABLE APP_WORKFLOW_TASKS
PROMPT ============================================================================

SET DEFINE OFF
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET VERIFY OFF

DECLARE
    l_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO l_exists
      FROM USER_TABLES
     WHERE TABLE_NAME='APP_WORKFLOW_TASKS';

    IF l_exists=0 THEN

        EXECUTE IMMEDIATE q'[
CREATE TABLE APP_WORKFLOW_TASKS
(
    TASK_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    WORKFLOW_ID     NUMBER NOT NULL,
    TASK_CODE       VARCHAR2(100 CHAR) NOT NULL,
    TASK_NAME       VARCHAR2(200 CHAR) NOT NULL,
    TASK_STATUS     VARCHAR2(30 CHAR) DEFAULT 'PENDING' NOT NULL,
    ASSIGNED_USER   VARCHAR2(100 CHAR),
    CREATED_DATE    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    COMPLETED_DATE  TIMESTAMP,
    CONSTRAINT CK_APP_WORKFLOW_TASK_STATUS
        CHECK (TASK_STATUS IN ('PENDING','RUNNING','COMPLETED','CANCELLED'))
)
]';

        DBMS_OUTPUT.PUT_LINE('APP_WORKFLOW_TASKS created.');

    ELSE

        DBMS_OUTPUT.PUT_LINE('APP_WORKFLOW_TASKS already exists.');

    END IF;
END;
/

COMMENT ON TABLE APP_WORKFLOW_TASKS IS 'Workflow tasks.';
COMMENT ON COLUMN APP_WORKFLOW_TASKS.TASK_ID IS 'Primary key.';
COMMENT ON COLUMN APP_WORKFLOW_TASKS.WORKFLOW_ID IS 'Workflow identifier.';
COMMENT ON COLUMN APP_WORKFLOW_TASKS.TASK_CODE IS 'Task code.';
COMMENT ON COLUMN APP_WORKFLOW_TASKS.TASK_NAME IS 'Task name.';
COMMENT ON COLUMN APP_WORKFLOW_TASKS.TASK_STATUS IS 'Task status.';
COMMENT ON COLUMN APP_WORKFLOW_TASKS.ASSIGNED_USER IS 'Assigned user.';
COMMENT ON COLUMN APP_WORKFLOW_TASKS.CREATED_DATE IS 'Creation timestamp.';
COMMENT ON COLUMN APP_WORKFLOW_TASKS.COMPLETED_DATE IS 'Completion timestamp.';

DECLARE
    l_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO l_exists
      FROM USER_INDEXES
     WHERE INDEX_NAME='IDX_APP_WORKFLOW_TASK_CODE';

    IF l_exists=0 THEN

        EXECUTE IMMEDIATE
            'CREATE INDEX IDX_APP_WORKFLOW_TASK_CODE
             ON APP_WORKFLOW_TASKS (TASK_CODE)
             TABLESPACE APEXONE_INDEX';

        DBMS_OUTPUT.PUT_LINE('IDX_APP_WORKFLOW_TASK_CODE created.');

    ELSE

        DBMS_OUTPUT.PUT_LINE('IDX_APP_WORKFLOW_TASK_CODE already exists.');

    END IF;
END;
/

DECLARE
    l_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO l_exists
      FROM USER_INDEXES
     WHERE INDEX_NAME='IDX_APP_WORKFLOW_TASK_STATUS';

    IF l_exists=0 THEN

        EXECUTE IMMEDIATE
            'CREATE INDEX IDX_APP_WORKFLOW_TASK_STATUS
             ON APP_WORKFLOW_TASKS (TASK_STATUS)
             TABLESPACE APEXONE_INDEX';

        DBMS_OUTPUT.PUT_LINE('IDX_APP_WORKFLOW_TASK_STATUS created.');

    ELSE

        DBMS_OUTPUT.PUT_LINE('IDX_APP_WORKFLOW_TASK_STATUS already exists.');

    END IF;
END;
/

COMMIT;

PROMPT Completed.

